[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Jakob Fischer <JakobFischer93@gmail.com>"]

[dependencies]
log = "0.4"
env_logger = "0.6"
chrono = "0.4"
num = "0.2"
allegro = "0.0.35"
allegro_primitives = "0.0.35"
rayon = "1.0"
