[package]
name = "explorer"
version = "0.1.0"
authors = ["Jakob Fischer <JakobFischer93@gmail.com>"]
edition = "2018"

[dependencies]
mandelbrot_core = { path = "../mandelbrot_core" }

log = "0.4"
env_logger = "0.6"
chrono = "0.4"
allegro = "0.0"
allegro_primitives = "0.0"
