[package]
name = "mandelbrot_core"
version = "0.1.0"
authors = ["Jakob Fischer <JakobFischer93@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.6"
chrono = "0.4"
num = "0.2"
rayon = "1.1"
image = "0.21"
palette = "0.4"
histogram = "0.6"
rand = "0.7"
